name: iOS CI workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore: '**.md'

concurrency:
  group: build-ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build and test app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          xcodebuild build-for-testing -project SwiftFashion.xcodeproj -scheme SwiftFashion -destination 'platform=iOS Simulator,name=iPhone 14'
      - name: Test
        run: |
          xcodebuild test-without-building -project SwiftFashion.xcodeproj -scheme SwiftFashion -destination 'platform=iOS Simulator,name=iPhone 14'
